# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: ElectronicArts.EAapp
PackageVersion: 12.218.0.5475
PackageLocale: it-IT
Publisher: Electronic Arts
PackageName: EA app
License: licenza MIT
Copyright: Copyright (c) Electronic Arts. All rights reserved.
ShortDescription: EA app
ManifestType: defaultLocale
ManifestVersion: 1.4.0
